export type JobType = "full-time" | "part-time" | "remote" | "contract";

export interface Job {
  id: string;
  title: string;
  company: string;
  companyLogoUrl: string | null;
  location: string;
  type: JobType;
  salaryMin: number | null;
  salaryMax: number | null;
  experienceLevel: string;
  category: string;
  postedDate: string;
  description: string;
  requirements: string[];
  isRemote: boolean;
}

export const JOBS: Job[] = [
  {
    id: "senior-backend-engineer",
    title: "Senior Backend Engineer",
    company: "Nimbus Labs",
    companyLogoUrl: null,
    location: "Bengaluru, India",
    type: "full-time",
    salaryMin: 28,
    salaryMax: 42,
    experienceLevel: "senior",
    category: "Engineering",
    postedDate: "2026-08-28",
    description:
      "Own the core API platform powering our distributed SaaS product. You'll design and scale services handling millions of requests a day, working closely with product and infrastructure teams.",
    requirements: [
      "5+ years building backend systems in Python or Go",
      "Strong SQL and experience with PostgreSQL or MySQL",
      "Hands-on with event-driven architecture (Kafka or similar)",
      "Comfortable with Docker, Kubernetes, and AWS",
    ],
    isRemote: false,
  },
  {
    id: "frontend-engineer",
    title: "Frontend Engineer",
    company: "Lumina Health",
    companyLogoUrl: null,
    location: "Remote",
    type: "remote",
    salaryMin: 22,
    salaryMax: 34,
    experienceLevel: "mid",
    category: "Engineering",
    postedDate: "2026-08-30",
    description:
      "Help build the patient-facing web experience for a telehealth platform. You'll craft fast, accessible React UIs and collaborate with designers on a growing design system.",
    requirements: [
      "3+ years with React and TypeScript",
      "Solid CSS and a practiced eye for detail",
      "Experience with state management and data fetching",
      "Understanding of accessibility and web performance",
    ],
    isRemote: true,
  },
  {
    id: "product-manager",
    title: "Product Manager",
    company: "Tidewater",
    companyLogoUrl: null,
    location: "New York, USA",
    type: "full-time",
    salaryMin: 130,
    salaryMax: 165,
    experienceLevel: "senior",
    category: "Product",
    postedDate: "2026-08-25",
    description:
      "Own the roadmap for our fintech analytics product. Work with customers, engineering, and design to define and ship features that move business metrics.",
    requirements: [
      "4+ years in product management, ideally B2B SaaS",
      "Strong analytical and prioritization skills",
      "Excellent written and verbal communication",
      "Experience shipping with agile teams",
    ],
    isRemote: false,
  },
  {
    id: "devops-engineer",
    title: "DevOps Engineer",
    company: "Orbital Systems",
    companyLogoUrl: null,
    location: "Berlin, Germany",
    type: "full-time",
    salaryMin: 70,
    salaryMax: 90,
    experienceLevel: "mid",
    category: "Engineering",
    postedDate: "2026-08-27",
    description:
      "Build and maintain our cloud infrastructure and CI/CD pipelines. You'll own reliability, observability, and deployment automation for a fast-moving platform.",
    requirements: [
      "3+ years with AWS or GCP",
      "Proficiency with Terraform and Kubernetes",
      "CI/CD automation experience (GitHub Actions, CircleCI)",
      "Linux fundamentals and scripting in Bash/Python",
    ],
    isRemote: false,
  },
  {
    id: "data-scientist",
    title: "Data Scientist",
    company: "Veridian Analytics",
    companyLogoUrl: null,
    location: "Remote",
    type: "remote",
    salaryMin: 95,
    salaryMax: 130,
    experienceLevel: "mid",
    category: "Data",
    postedDate: "2026-08-22",
    description:
      "Apply statistical modeling and ML to customer behavior data. Partner with product teams to turn insight into features that drive retention and growth.",
    requirements: [
      "3+ years in applied data science",
      "Strong Python and SQL",
      "Experience with ML frameworks like scikit-learn or PyTorch",
      "Comfort presenting findings to non-technical stakeholders",
    ],
    isRemote: true,
  },
  {
    id: "ux-designer",
    title: "UX Designer",
    company: "Frame & Fork",
    companyLogoUrl: null,
    location: "London, UK",
    type: "contract",
    salaryMin: 55,
    salaryMax: 70,
    experienceLevel: "mid",
    category: "Design",
    postedDate: "2026-08-29",
    description:
      "Design intuitive, beautiful flows for a food-tech marketplace. This is a 6-month contract with a strong chance of extension for the right person.",
    requirements: [
      "4+ years of product/UX design",
      "Strong portfolio demonstrating end-to-end product design",
      "Proficiency with Figma",
      "Experience running user research",
    ],
    isRemote: false,
  },
  {
    id: "mobile-engineer",
    title: "Mobile Engineer (iOS)",
    company: "PocketPay",
    companyLogoUrl: null,
    location: "Hyderabad, India",
    type: "full-time",
    salaryMin: 24,
    salaryMax: 36,
    experienceLevel: "mid",
    category: "Engineering",
    postedDate: "2026-08-31",
    description:
      "Build delightful iOS experiences for a payments super-app used by millions. Focus on performance, reliability, and a polished user experience.",
    requirements: [
      "3+ years of iOS development in Swift",
      "Understanding of the iOS app lifecycle and best practices",
      "Experience with REST APIs and offline-first patterns",
      "Familiarity with SwiftUI a plus",
    ],
    isRemote: false,
  },
  {
    id: "marketing-manager",
    title: "Growth Marketing Manager",
    company: "Brightpath",
    companyLogoUrl: null,
    location: "Remote",
    type: "remote",
    salaryMin: 80,
    salaryMax: 105,
    experienceLevel: "senior",
    category: "Marketing",
    postedDate: "2026-08-24",
    description:
      "Own paid acquisition and lifecycle marketing for an ed-tech platform. You'll drive measurable growth across channels and experiment relentlessly.",
    requirements: [
      "4+ years in growth or performance marketing",
      "Hands-on with paid social and search",
      "Strong comfort with analytics and attribution",
      "Experience with marketing automation tools",
    ],
    isRemote: true,
  },
  {
    id: "sales-engineer",
    title: "Sales Engineer",
    company: "DataHarbor",
    companyLogoUrl: null,
    location: "Austin, USA",
    type: "full-time",
    salaryMin: 110,
    salaryMax: 140,
    experienceLevel: "mid",
    category: "Sales",
    postedDate: "2026-08-21",
    description:
      "Partner with the sales team as a technical expert during the deal cycle. Run demos, build proofs-of-concept, and address technical objections.",
    requirements: [
      "3+ years in a technical sales or presales role",
      "Comfortable with SQL and APIs",
      "Excellent presentation and interpersonal skills",
      "Willingness to travel ~30% of the time",
    ],
    isRemote: false,
  },
  {
    id: "fullstack-developer",
    title: "Full Stack Developer",
    company: "CedarWorks",
    companyLogoUrl: null,
    location: "Toronto, Canada",
    type: "full-time",
    salaryMin: 85,
    salaryMax: 115,
    experienceLevel: "mid",
    category: "Engineering",
    postedDate: "2026-08-19",
    description:
      "Build end-to-end features for a construction project management tool. Work across a React frontend and a Node.js backend.",
    requirements: [
      "3+ years of full stack development",
      "Proficiency with React and Node.js/TypeScript",
      "Experience with relational databases",
      "Comfort with Git and CI/CD workflows",
    ],
    isRemote: false,
  },
  {
    id: "ml-engineer",
    title: "Machine Learning Engineer",
    company: "Axiom AI",
    companyLogoUrl: null,
    location: "Singapore",
    type: "full-time",
    salaryMin: 120,
    salaryMax: 160,
    experienceLevel: "senior",
    category: "Data",
    postedDate: "2026-08-18",
    description:
      "Train and deploy production ML models that power our recommendation engine. Own the full lifecycle from experimentation to serving.",
    requirements: [
      "5+ years in ML engineering",
      "Deep knowledge of Python and frameworks like PyTorch",
      "Experience with MLOps and model serving at scale",
      "Familiarity with large language models is a plus",
    ],
    isRemote: false,
  },
  {
    id: "technical-writer",
    title: "Technical Writer",
    company: "DocuBridge",
    companyLogoUrl: null,
    location: "Remote",
    type: "part-time",
    salaryMin: 40,
    salaryMax: 52,
    experienceLevel: "mid",
    category: "Content",
    postedDate: "2026-08-20",
    description:
      "Write clear developer documentation, API references, and tutorials for our platform SDK. You'll turn complex concepts into approachable guides.",
    requirements: [
      "3+ years writing technical documentation",
      "Ability to read code (JavaScript/Python) for context",
      "Stellar written English and attention to detail",
      "Experience with Git and markdown publishing",
    ],
    isRemote: true,
  },
  {
    id: "qa-engineer",
    title: "QA Engineer",
    company: "PixelForge",
    companyLogoUrl: null,
    location: "Pune, India",
    type: "full-time",
    salaryMin: 16,
    salaryMax: 24,
    experienceLevel: "mid",
    category: "Engineering",
    postedDate: "2026-08-17",
    description:
      "Design and maintain automated test suites for our web platform. Champion quality across the engineering org and own the release process.",
    requirements: [
      "2+ years in software QA",
      "Experience with Playwright or Cypress",
      "Familiarity with API testing and CI integration",
      "Strong attention to edge cases",
    ],
    isRemote: false,
  },
  {
    id: "customer-success",
    title: "Customer Success Manager",
    company: "RelayCRM",
    companyLogoUrl: null,
    location: "Sydney, Australia",
    type: "full-time",
    salaryMin: 90,
    salaryMax: 110,
    experienceLevel: "senior",
    category: "Support",
    postedDate: "2026-08-16",
    description:
      "Drive adoption and retention for our CRM platform across strategic accounts. Be the voice of the customer and own renewal conversations.",
    requirements: [
      "4+ years in customer success or account management",
      "Comfort speaking with technical and executive audiences",
      "Strong relationship-building skills",
      "Familiarity with SaaS metrics like NPS and churn",
    ],
    isRemote: false,
  },
  {
    id: "security-engineer",
    title: "Security Engineer",
    company: "Sentinel One",
    companyLogoUrl: null,
    location: "Remote",
    type: "remote",
    salaryMin: 120,
    salaryMax: 155,
    experienceLevel: "senior",
    category: "Engineering",
    postedDate: "2026-08-15",
    description:
      "Harden our cloud infrastructure and application security posture. Perform threat modeling, run security reviews, and respond to incidents.",
    requirements: [
      "5+ years in security engineering",
      "Deep knowledge of AWS/GCP security controls",
      "Experience with application security and OWASP",
      "Familiarity with compliance frameworks (SOC2, ISO 27001)",
    ],
    isRemote: true,
  },
  {
    id: "java-developer",
    title: "Java Developer",
    company: "CoreStack",
    companyLogoUrl: null,
    location: "Noida, India",
    type: "full-time",
    salaryMin: 18,
    salaryMax: 28,
    experienceLevel: "mid",
    category: "Engineering",
    postedDate: "2026-08-29",
    description:
      "Build enterprise backend services in Java and Spring Boot. You'll own microservices that power procurement workflows for large enterprises.",
    requirements: [
      "3+ years with Java and Spring Boot",
      "Experience building REST APIs",
      "Familiarity with Kafka and distributed systems",
      "Understanding of SQL and database design",
    ],
    isRemote: false,
  },
  {
    id: "hr-business-partner",
    title: "HR Business Partner",
    company: "Northgate",
    companyLogoUrl: null,
    location: "Chicago, USA",
    type: "full-time",
    salaryMin: 95,
    salaryMax: 120,
    experienceLevel: "mid",
    category: "People",
    postedDate: "2026-08-23",
    description:
      "Partner with engineering and G&A leadership on people strategy, performance, and culture. Coach managers and support org health.",
    requirements: [
      "5+ years of HRBP experience",
      "Strong coaching and facilitation skills",
      "Experience with performance management programs",
      "Comfort with compensation and talent planning",
    ],
    isRemote: false,
  },
  {
    id: "react-native-dev",
    title: "React Native Developer",
    company: "Fleetline",
    companyLogoUrl: null,
    location: "Remote",
    type: "contract",
    salaryMin: 65,
    salaryMax: 80,
    experienceLevel: "mid",
    category: "Engineering",
    postedDate: "2026-08-26",
    description:
      "Build cross-platform logistics apps in React Native. 9-month contract connected to our core platform team.",
    requirements: [
      "3+ years of React Native",
      "Experience with app stores and release management",
      "Understanding of mobile networking and caching",
      "Bonus: experience with maps/location services",
    ],
    isRemote: true,
  },
  {
    id: "financial-analyst",
    title: "Financial Analyst",
    company: "Vantage Capital",
    companyLogoUrl: null,
    location: "Mumbai, India",
    type: "full-time",
    salaryMin: 20,
    salaryMax: 30,
    experienceLevel: "mid",
    category: "Finance",
    postedDate: "2026-08-28",
    description:
      "Support investment decisions with rigorous financial modeling and market analysis. Prepare reports for the investment committee.",
    requirements: [
      "2+ years in financial analysis or investment banking",
      "Advanced Excel and financial modeling",
      "Strong analytical and presentation skills",
      "CFA progress a plus",
    ],
    isRemote: false,
  },
  {
    id: "content-strategist",
    title: "Content Strategist",
    company: "Paperplane",
    companyLogoUrl: null,
    location: "Remote",
    type: "part-time",
    salaryMin: 45,
    salaryMax: 58,
    experienceLevel: "mid",
    category: "Content",
    postedDate: "2026-08-14",
    description:
      "Lead content strategy for our editorial team. Plan calendars, define voice, and align content with growth goals across channels.",
    requirements: [
      "4+ years in content marketing or strategy",
      "Excellent writing and editorial judgment",
      "Experience with SEO best practices",
      "Ability to run content experiments",
    ],
    isRemote: true,
  },
  {
    id: "site-reliability",
    title: "Site Reliability Engineer",
    company: "Falcon Cloud",
    companyLogoUrl: null,
    location: "Tokyo, Japan",
    type: "full-time",
    salaryMin: 110,
    salaryMax: 145,
    experienceLevel: "senior",
    category: "Engineering",
    postedDate: "2026-08-13",
    description:
      "Keep our global platform reliable and fast. Own SLOs, incident response, and capacity planning for a high-traffic cloud service.",
    requirements: [
      "5+ years in SRE or platform engineering",
      "Deep Kubernetes and cloud experience",
      "Strong automation and scripting skills",
      "Experience with observability tooling (Prometheus, Grafana)",
    ],
    isRemote: false,
  },
  {
    id: "account-executive",
    title: "Account Executive",
    company: "SalesForward",
    companyLogoUrl: null,
    location: "Austin, USA",
    type: "full-time",
    salaryMin: 85,
    salaryMax: 110,
    experienceLevel: "mid",
    category: "Sales",
    postedDate: "2026-08-12",
    description:
      "Own the full sales cycle for mid-market accounts. Prospect, demo, negotiate, and close new business for our revenue platform.",
    requirements: [
      "3+ years in closing sales roles",
      "Proven track record of hitting quota",
      "Strong pipeline discipline with a CRM",
      "Excellent communication skills",
    ],
    isRemote: false,
  },
  {
    id: "ios-contract",
    title: "Lead iOS Engineer",
    company: "Skylark",
    companyLogoUrl: null,
    location: "Remote",
    type: "contract",
    salaryMin: 90,
    salaryMax: 110,
    experienceLevel: "senior",
    category: "Engineering",
    postedDate: "2026-08-11",
    description:
      "Lead a small team building a consumer iOS app. 6-month contract with path to full-time. You'll set technical direction and ship.",
    requirements: [
      "6+ years of iOS engineering",
      "Extensive Swift and SwiftUI experience",
      "Experience leading or mentoring engineers",
      "Strong product instinct",
    ],
    isRemote: true,
  },
  {
    id: "data-engineer",
    title: "Data Engineer",
    company: "Streamline Data",
    companyLogoUrl: null,
    location: "Amsterdam, NL",
    type: "full-time",
    salaryMin: 85,
    salaryMax: 110,
    experienceLevel: "mid",
    category: "Data",
    postedDate: "2026-08-10",
    description:
      "Design and maintain data pipelines feeding our analytics and ML platform. Own the warehouse schema and data quality.",
    requirements: [
      "3+ years in data engineering",
      "Strong SQL and Python",
      "Experience with dbt and Airflow",
      "Familiarity with Snowflake or BigQuery",
    ],
    isRemote: false,
  },
  {
    id: "brand-designer",
    title: "Brand Designer",
    company: "Oak & Ember",
    companyLogoUrl: null,
    location: "Portland, USA",
    type: "part-time",
    salaryMin: 50,
    salaryMax: 62,
    experienceLevel: "mid",
    category: "Design",
    postedDate: "2026-08-09",
    description:
      "Own visual identity and marketing design for a consumer brand. Create assets across web, email, and social.",
    requirements: [
      "4+ years of brand or graphic design",
      "A strong, cohesive portfolio",
      "Proficiency with Figma and Adobe CC",
      "Excellent typography skills",
    ],
    isRemote: false,
  },
  {
    id: "product-designer-2",
    title: "Product Designer",
    company: "Loopback",
    companyLogoUrl: null,
    location: "San Francisco, USA",
    type: "full-time",
    salaryMin: 130,
    salaryMax: 160,
    experienceLevel: "senior",
    category: "Design",
    postedDate: "2026-08-08",
    description:
      "Design core workflows for a developer tools product. Own problems end-to-end from research to polished UI.",
    requirements: [
      "5+ years of product design",
      "Strong portfolio of shipped software",
      "Experience designing for technical audiences",
      "Proficiency with Figma",
    ],
    isRemote: false,
  },
  {
    id: "devrel",
    title: "Developer Relations Engineer",
    company: "PicoTerra",
    companyLogoUrl: null,
    location: "Remote",
    type: "remote",
    salaryMin: 100,
    salaryMax: 125,
    experienceLevel: "mid",
    category: "Engineering",
    postedDate: "2026-08-07",
    description:
      "Be the bridge between our engineering team and the developer community. Write content, build samples, and support open source.",
    requirements: [
      "3+ years as an engineer or developer advocate",
      "Comfortable writing and speaking publicly",
      "Strong JavaScript or Python skills",
      "Active in developer communities",
    ],
    isRemote: true,
  },
  {
    id: "recruiter",
    title: "Technical Recruiter",
    company: "TalentLink",
    companyLogoUrl: null,
    location: "Denver, USA",
    type: "full-time",
    salaryMin: 75,
    salaryMax: 95,
    experienceLevel: "mid",
    category: "People",
    postedDate: "2026-08-06",
    description:
      "Own full-cycle recruiting for engineering roles. Source, screen, and shepherd candidates through a smooth interview process.",
    requirements: [
      "3+ years of technical recruiting",
      "Strong sourcing skills (LinkedIn, GitHub)",
      "Excellent candidate experience focus",
      "Familiarity with ATS tools",
    ],
    isRemote: false,
  },
  {
    id: "backend-go",
    title: "Backend Engineer (Go)",
    company: "Cascade",
    companyLogoUrl: null,
    location: "Remote",
    type: "remote",
    salaryMin: 105,
    salaryMax: 135,
    experienceLevel: "senior",
    category: "Engineering",
    postedDate: "2026-08-30",
    description:
      "Design high-throughput services in Go that power our realtime platform. Own reliability and performance end-to-end.",
    requirements: [
      "5+ years in backend engineering",
      "Production experience with Go",
      "Deep understanding of distributed systems",
      "Experience with Kubernetes and cloud infrastructure",
    ],
    isRemote: true,
  },
  {
    id: "finance-controller",
    title: "Finance Controller",
    company: "Hearthstone",
    companyLogoUrl: null,
    location: "London, UK",
    type: "full-time",
    salaryMin: 90,
    salaryMax: 115,
    experienceLevel: "senior",
    category: "Finance",
    postedDate: "2026-08-05",
    description:
      "Own financial reporting, budgeting, and compliance for a growing SaaS business. Manage the finance team and close processes.",
    requirements: [
      "6+ years in accounting or finance",
      "Experience as a controller or finance lead",
      "Strong knowledge of UK GAAP / IFRS",
      "Experience with SaaS revenue recognition",
    ],
    isRemote: false,
  },
  {
    id: "solutions-architect",
    title: "Solutions Architect",
    company: "GridPoint",
    companyLogoUrl: null,
    location: "Singapore",
    type: "full-time",
    salaryMin: 115,
    salaryMax: 145,
    experienceLevel: "senior",
    category: "Engineering",
    postedDate: "2026-08-04",
    description:
      "Design sophisticated solutions for enterprise customers on our analytics platform. Lead technical discovery and architecture workshops.",
    requirements: [
      "5+ years in a solutions or enterprise architecture role",
      "Broad knowledge of modern cloud architecture",
      "Strong stakeholder communication skills",
      "Experience with data platforms",
    ],
    isRemote: false,
  },
  {
    id: "community-manager",
    title: "Community Manager",
    company: "Gatherly",
    companyLogoUrl: null,
    location: "Remote",
    type: "part-time",
    salaryMin: 40,
    salaryMax: 50,
    experienceLevel: "mid",
    category: "Marketing",
    postedDate: "2026-08-03",
    description:
      "Grow and nurture our online community across forums and social. Plan events, moderate conversations, and surface user feedback.",
    requirements: [
      "3+ years in community management",
      "Excellent written communication",
      "Experience planning virtual events",
      "Comfortable with Discord and social platforms",
    ],
    isRemote: true,
  },
  {
    id: "cloud-computing",
    title: "Cloud Solutions Engineer",
    company: "Zephyr Telecom",
    companyLogoUrl: null,
    location: "Dubai, UAE",
    type: "full-time",
    salaryMin: 90,
    salaryMax: 115,
    experienceLevel: "mid",
    category: "Engineering",
    postedDate: "2026-08-02",
    description:
      "Operate and optimize cloud infrastructure for telecom clients. Automate provisioning, monitoring, and cost controls.",
    requirements: [
      "4+ years with AWS or Azure",
      "Terraform and infrastructure-as-code experience",
      "Strong Linux administration",
      "Experience with cloud cost optimization",
    ],
    isRemote: false,
  },
  {
    id: "staff-data-scientist",
    title: "Staff Data Scientist",
    company: "Northwind",
    companyLogoUrl: null,
    location: "Remote",
    type: "remote",
    salaryMin: 150,
    salaryMax: 185,
    experienceLevel: "senior",
    category: "Data",
    postedDate: "2026-08-01",
    description:
      "Lead complex modeling initiatives and mentor a team of data scientists. Drive technical strategy for our personalization platform.",
    requirements: [
      "7+ years in data science",
      "Strong causal inference and experimentation",
      "Experience leading technical initiatives",
      "Deep Python and ML expertise",
    ],
    isRemote: true,
  },
  {
    id: "accounting-manager",
    title: "Accounting Manager",
    company: "Bellwether",
    companyLogoUrl: null,
    location: "Remote",
    type: "remote",
    salaryMin: 80,
    salaryMax: 100,
    experienceLevel: "mid",
    category: "Finance",
    postedDate: "2026-07-31",
    description:
      "Manage the day-to-day accounting operations and month-end close. Own reconciliations, AP/AR, and reporting.",
    requirements: [
      "4+ years in accounting",
      "CPA or equivalent a plus",
      "Experience with NetSuite or QuickBooks",
      "Strong attention to detail",
    ],
    isRemote: true,
  },
  {
    id: "devops-contract",
    title: "Platform Engineer (Contract)",
    company: "Helix",
    companyLogoUrl: null,
    location: "Remote",
    type: "contract",
    salaryMin: 85,
    salaryMax: 100,
    experienceLevel: "senior",
    category: "Engineering",
    postedDate: "2026-07-30",
    description:
      "Help our platform team migrate services to Kubernetes and build internal developer tooling. 4-month engagement.",
    requirements: [
      "5+ years in platform/DevOps engineering",
      "Strong Kubernetes and Helm skills",
      "Experience with CI/CD and developer tooling",
      "Terraform proficiency",
    ],
    isRemote: true,
  },
  {
    id: "frontend-contract",
    title: "Frontend Engineer (Contract)",
    company: "Brightline",
    companyLogoUrl: null,
    location: "Remote",
    type: "contract",
    salaryMin: 60,
    salaryMax: 75,
    experienceLevel: "mid",
    category: "Engineering",
    postedDate: "2026-07-29",
    description:
      "Rebuild the marketing site in Next.js with a design system. 3-month contract focused on a fast, polished, accessible experience.",
    requirements: [
      "3+ years with React and TypeScript",
      "Experience with Next.js and Tailwind CSS",
      "Strong attention to design quality",
      "Understanding of Core Web Vitals",
    ],
    isRemote: true,
  },
  {
    id: "data-analyst-2",
    title: "Data Analyst",
    company: "MetricMinds",
    companyLogoUrl: null,
    location: "Mexico City, Mexico",
    type: "full-time",
    salaryMin: 35,
    salaryMax: 48,
    experienceLevel: "mid",
    category: "Data",
    postedDate: "2026-07-28",
    description:
      "Turn data into decisions for our product and marketing teams. Build dashboards, run analyses, and communicate insights clearly.",
    requirements: [
      "2+ years in data analysis",
      "Strong SQL and a BI tool (Looker, Tableau)",
      "Comfort with Python or R",
      "Excellent communication and storytelling",
    ],
    isRemote: false,
  },
];
